server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: device-management
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:h2:file:~/algasensors-device-management-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true

rest-client:
  sensor-monitoring-client:
    baseUrl: http://localhost:8082
    read-timeout: 30000
    connect-timeout: 30000